version: '2'
services:
    webinarapp-app:
        image: webinarapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://webinarapp-mysql:3306/webinarapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=webinarapp-elasticsearch:9300
        ports:
            - 8080:8080
    webinarapp-mysql:
        extends:
            file: mysql.yml
            service: webinarapp-mysql
    webinarapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: webinarapp-elasticsearch
